version: '3'

services:
  mysql-server:
    image: mysql:5.7
    hostname: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: nicosalvo
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    networks:
      - tp-dam
    ports:
      - '3306:3306'

  mysql-admin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: nicosalvo
    networks:
      - tp-dam
    depends_on:
      - mysql-server
    ports:
      - '8001:80'

networks:
  tp-dam:
    driver: bridge
