@api =  http://localhost:3000/devices
@contentType = application/json
@date = {{$datetime iso8601}}

GET {{api}}

###
GET {{api}}/1

###
GET {{api}}/1/measurements

###
GET {{api}}/1/irrigation-log

###
GET {{api}}/count

###
POST {{api}}
Content-Type: {{contentType}}

{
  "name": "task 4",
  "location": "some desc 4",
  "solenoid_valve_id": 7
}

###
POST {{api}}/measurement
Content-Type: {{contentType}}

{
  "_date": "{{date}}",
  "_value": 30,
  "_deviceId": 7
}

###
DELETE {{api}}/7

###
PUT {{api}}/1
Content-Type: {{contentType}}

{
  "name": "Sensor 1"
}